[package]
name = "ordered-float"
version = "1.0.0"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>", "Matt Brubeck <mbrubeck@limpet.net>"]
license = "MIT"
description = "Wrappers for total ordering on floats"
repository = "https://github.com/reem/rust-ordered-float"
readme = "README.md"

[dependencies]
num-traits = "0.2"
serde = { version = "1.0", optional = true }

[dev-dependencies]
serde_test = "1.0"
